name          'puppet-xltestview'
version       '0.0.1'
source        'https://github.com/WianVos/puppet-xltestview.git'
author        'Wian Vos'
license       'Apache 2.0'
summary       'A module to install and configure xl-testview'
description   ''
project_page  'https://github.com/WianVos/puppet-xltestview'

dependency 'puppetlabs/stdlib'
